{
 "title": "Jaeger",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "traceId" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count{http_response_status_code=~\"500\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "View Logs",
   "type": "table",
   "gridPos": { "h": 14, "w": 20, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Logs",
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "traceId=$traceId",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "View Trace",
   "type": "traces",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 30 },
   "targets": [
    { "query": "${traceId}" }
   ]
  },
  {
   "title": "Response Time > 100ms",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 48 },
   "targets": [
    { "minDuration": "100ms", "operation": "GET api/WeatherForecast", "service": "OpensearchJaegerWebAPI", "tags": "http.response.status_code=200" }
   ]
  }
 ]
}